// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxGV0HHlWMEBdqwOKakAbhcw4gaFr5IC4',
    appId: '1:755745348541:web:711a5d868bba650198d0d4',
    messagingSenderId: '755745348541',
    projectId: 'code-sliver',
    authDomain: 'code-sliver.firebaseapp.com',
    storageBucket: 'code-sliver.appspot.com',
    measurementId: 'G-G0M1JRZGCR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXnZFzYeQG5Me-nJ1n0mFZaiG3NgOqZGU',
    appId: '1:755745348541:android:d262d8beb2524d9a98d0d4',
    messagingSenderId: '755745348541',
    projectId: 'code-sliver',
    storageBucket: 'code-sliver.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqdUw5chzMjLue0wnXooVfN-At4OtOupI',
    appId: '1:755745348541:ios:73e5606ce1ff80fe98d0d4',
    messagingSenderId: '755745348541',
    projectId: 'code-sliver',
    storageBucket: 'code-sliver.appspot.com',
    iosBundleId: 'com.example.codeSliver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqdUw5chzMjLue0wnXooVfN-At4OtOupI',
    appId: '1:755745348541:ios:9d020abeb0e1001d98d0d4',
    messagingSenderId: '755745348541',
    projectId: 'code-sliver',
    storageBucket: 'code-sliver.appspot.com',
    iosBundleId: 'com.example.codeSliver.RunnerTests',
  );
}
